routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('contacts', 'ContactController@index');

Route::get('contacts/create', 'ContactController@create');

Route::get('/contacts/{id}/delete','ContactController@destroy')->name('contacts.destroy');

Route::post('contactsaction', 'ContactController@storeContact');

Route::get('contacts/{id}/edit', 'ContactController@edit')->name('contacts.edit');

Route::get('contacts/{id}/destroy', 'ContactController@destroy')->name('contacts.destroy');

Route::post('contacts/{id}/update','ContactController@update')->name('contacts.update');

Route::get('contacts/export', 'ContactController@export')->name('contacts.export');

Route::get('importExportView', 'ContactController@importExportView');

Route::post('contacts/import', 'ContactController@import')->name('contacts/import');

Route::post('contacts/addtogroup', 'GroupController@store');

Route::get('contacts/createGroup', 'GroupController@createGroup')->name('contacts/group');

Route::get('contacts/groups', 'GroupController@showGroups');

Route::get('groups/{id}/editGroup', 'GroupController@edit')->name('groups.editGroup');

Route::get('groups/{id}/destroy', 'GroupController@destroy')->name('groups.destroy');

Route::post('groups/{id}/update','GroupController@update')->name('groups.update');


// Campaigns
Route::resource('campaigns', 'CampaignController');

app/Campaign.php
<?php

namespace App;

use Illuminate\Support\Facades\Storage;

use Illuminate\Database\Eloquent\Model;

class Campaign extends Model
{
    //Relations
    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function contacts()
    {
        return $this->belongsToMany('App\ContactModel', 'compaign_contact');

    }

    // Helpers
    public function deleteLogo()
    {
        if (Storage::disk('local')->exists('logos/'.$this->image)) {
            Storage::disk('local')->delete('logos/'.$this->image);
        }

        return true;
    }
}

app/Http/Controllers/CampaignController.php
<?php

namespace App\Http\Controllers;

use App\Campaign;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class CampaignController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    // Hashing function for the image name
    public function hashImageName($image)
    {
        return md5($image->getClientOriginalName() . uniqid('weband')) . '.' . $image->getClientOriginalExtension();
    }

    /**
     * CampaignController constuctor
     */

    public function __construct()
    {
        $this->middleware('auth');
    }


    /**
     * Display a listing of the resource.
     * @return \illuminate\Http\Response
     */
    public function index()
    {
        $campaigns = Auth::user()->campaigns;

        return view('campaigns.index', compact('campaigns'));
    }



    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $contacts = Auth::user()->contacts;
        $groups = Auth::user()->groups;

        return view('campaigns.create', compact('groups', 'contacts'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        $campaign = new Campaign;
        $campaign->user()->associate(Auth::user());
        $campaign->name = $request->name;
        $campaign->from = $request->from;
        $campaign->subject = $request->subject;
        $campaign->title = $request->title;
        $campaign->text = $request->text;
        $campaign->button_text = $request->button_text;
        $campaign->button_color = $request->button_color;

        //Check if image is presented in the request and it's valid
        if ($request->hasFile('logo') && $request->logo->isvalid()) {
            $logo = $request->logo;
            $image_name = $this->hashImageName($logo);

            //storage the image in filesystem
            Storage::disk('local')->putFileAs('logos', $logo, $image_name);

            //Storage the path as thext in the database
            $campaign->logo = $image_name;
        }

        $campaign->save();

        $campaign->contacts()->attach($request->contacts);

        return redirect()->route('campaigns.index')->with('Success', 'Contact added successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Campaign  $campaign
     * @return \Illuminate\Http\Response
     */
    public function show(Campaign $campaign)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Campaign  $campaign
     * @return \Illuminate\Http\Response
     */
    public function edit(Campaign $campaign)
    {
      
        $contacts = Auth::user()->contacts;
        $groups = Auth::user()->groups;

        return view('campaigns.edit', compact('campaign', 'contacts', 'groups'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Campaign  $campaign
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Campaign $campaign)
    {

        $campaign->name = $request->name;
        $campaign->from = $request->from;
        $campaign->subject = $request->subject;
        $campaign->title = $request->title;
        $campaign->text = $request->text;
        $campaign->button_text = $request->button_text;
        $campaign->button_color = $request->button_color;

        if ($request->hasFile('logo') && $request->logo->isValid()) {
            $logo = $request->logo;
            $image_name = $this->hashImageName($logo);

            //storage the image in filesystem
            Storage::disk('local')->putFileAs('logos', $logo, $image_name);


            //Storage the path as thext in the database
            
            
            $campaign->deleteLogo();
            
            $campaign->logo = $image_name;
            
            
        }
        
        $campaign->save();
        $campaign->contacts()->sync($request->contacts);
        
        return redirect()->route('campaigns.index')->with('Success', 'Contact added successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Campaign  $campaign
     * @return \Illuminate\Http\Response
     */
    public function destroy(Campaign $campaign)
    {
        $campaign->deleteLogo();
        $campaign->delete();

        return redirect()->back()->with('success', 'Кампанията беше изтрита');
    }
}

resources/views/campaigns/create.blade.php
@extends('layouts.master')
@section('title','Create Contact')
@section('content')
<div class="row mt-5">
  <div class="col-sm-8 offset-sm-2">
    <form action="{{ route('campaigns.store') }}" method="POST" enctype="multipart/form-data" data-redirect="{{ route('campaigns.index') }}">
      @csrf
      <div class=" form-group">
      <label>Name:</label>
      <input type="text" name="name" id="name" class="form-control" required>
  </div>
  <div class="form-group">
    <label>From (Email):</label>
    <input type="email" name="from" id="from" class="form-control" required>
  </div>
  <div class="form-group">
    <label>Subject</label>
    <input type="text" name="subject" id="subject" class="form-control" required>
  </div>

  <div class="form-group">
    <label>Title:</label>
    <input type="text" name="title" id="title" class="form-control" required>
  </div>

  <div class="form-group">
    <label>Text</label>
    <input type="text" name="button_text" id="button_text" class="form-control" required>
  </div>

  <div class="form-group">
    <label>Color:</label>
    <input type="color" name="button_color" id="button_color" class="form-control" required>
  </div>

  <div class="form-group">
    <label>Logo:</label>
    <input type="file" accept="png, jpg, jpeg, svg, gif" name="logo" id="logo" class="form-control" required>
  </div>



  <div class="form-group">
    <h5>Choose recipient:</h5>
  </div>

  <div class="form-group">
    <label for="group">Choose contacts from group:</label>

    <select id="group" class="form-control" style="width: 100%; margin-bottom: 20px;">
      @foreach($groups as $group)

      <option value="{{ $group->id }}">{{ $group->group_name }}</option>
      @endforeach
    </select>

  </div>


  <button type="submit" class="btn btn-success">Submit</button>
  </form>

</div>
@endsection

resources/views/campaigns/edit.blade.php
@extends('layouts.master')
@section('title','Create Contact')
@section('content')
<div class="row mt-5">
  <div class="col-sm-8 offset-sm-2">
    <form action="{{ route('campaigns.update' , $campaign->id) }}" method="POST" enctype="multipart/form-data" data-redirect="{{ route('campaigns.index') }}">
      @csrf
      @method('PUT')

      <div class=" form-group">
      <label>Name:</label>
      <input type="text" name="name" id="name" class="form-control" required>
  </div>
  <div class="form-group">
    <label>From (Email):</label>
    <input type="email" name="from" id="from" class="form-control" required>
  </div>
  <div class="form-group">
    <label>Subject</label>
    <input type="text" name="subject" id="subject" class="form-control" required>
  </div>

  <div class="form-group">
    <label>Title:</label>
    <input type="text" name="title" id="title" class="form-control" required>
  </div>

  <div class="form-group">
    <label>Text</label>
    <input type="text" name="button_text" id="button_text" class="form-control" required>
  </div>

  <div class="form-group">
    <label>Color:</label>
    <input type="color" name="button_color" id="button_color" class="form-control" required>
  </div>

  <div class="form-group">
    <label>Logo:</label>
    <input type="file" accept="png, jpg, jpeg, svg, gif" name="logo" id="logo" class="form-control" required>
  </div>



  <div class="form-group">
    <h5>Choose recipient:</h5>
  </div>

  <div class="form-group">
    <label for="group">Choose contacts from group:</label>

    <select id="group" class="form-control" style="width: 100%; margin-bottom: 20px;">
      @foreach($groups as $group)

      <option value="{{ $group->id }}">{{ $group->group_name }}</option>
      @endforeach
    </select>

  </div>


  <button type="submit" class="btn btn-success">Submit</button>
  </form>

</div>
@endsection

resources/views/campaigns/index.blade.php
@extends('layouts.master')
@section('title','contacts Index')
@section('content')
<hr>

<br>
<hr>
<div class="row">
  <div class="col-sm-12">
    <table class="table">
      <tr class="text-center">
        <th>Name</th>
        <th>From</th>
        <th>Subject</th>
        <th>Аctions</th>
      </tr>

      @foreach($campaigns as $campaign)
      <tr class="text-center">
        <td>{{ $campaign->name }}</td>
        <td>{{ $campaign->from }}</td>
        <td>{{ $campaign->subject }}</td>
        <td><a href="{{ route('campaigns.edit', $campaign->id )}}" class="btn btn-info">Edit</a></td>
        <td>
          <form class="delete" action="{{ route('campaigns.destroy', $campaign->id) }}" method="POST">
            <input type="hidden" name="_method" value="DELETE">
            {{ csrf_field() }}
            <input type="submit" value="Delete">
          </form>
        </td>
      </tr>
      @endforeach
    </table>
  </div>


  <br>
</div>

<script>
    $(".delete").on("submit", function(){
        return confirm("Are you sure?");
    });
</script>

@endsection